### ISSUE TITLE
Releases no longer on GitHub?

### ISSUE THREAD

**Issue by Peedee2002** [iElden/MultiplayerHelper#9]
Before 1.5, there were releases for each version on GitHub, which I relied on because I use Epic instead of Steam. I think there are ways for me to get around this, but if it is simple - is it possible to get the releases on GitHub as they are released on steam?

**Comment by iElden** [comment]
Hi, I am no longer the maintenair of the mod, you can find newer version here :
https://github.com/CivilizationVIBetterBalancedGame/MultiplayerHelper/releases
